/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Aplikasi;
import Model.Pasien;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author Ganis, Dhino
 */
public class formRegistrasiPasien extends javax.swing.JFrame implements ActionListener {

    Aplikasi model;
    Pasien pasien;
    /**
     * Creates new form formRegistrasiPasien
     */
    public formRegistrasiPasien(Aplikasi model) {
        initComponents();
        this.model = model;
        this.setLocationRelativeTo(null);
        this.setTitle("Registasi Pasien");
        
        this.setVisible(true);
        this.addListener(this);
        
        this.pasien = null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel_Nama = new javax.swing.JLabel();
        jLabel_NIM = new javax.swing.JLabel();
        jTextField_Nama = new javax.swing.JTextField();
        jTextFiel_NIM = new javax.swing.JTextField();
        jButton_OK = new javax.swing.JButton();
        jButton_Kembali = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField_umur = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPassField1_pwd = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Registrasi");

        jLabel_Nama.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_Nama.setText("Nama  :");

        jLabel_NIM.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_NIM.setText("NIM   :");

        jButton_OK.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton_OK.setText("Register");

        jButton_Kembali.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton_Kembali.setText("Kembali");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Umur  :");

        jTextField_umur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_umurActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Password :");

        jPassField1_pwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPassField1_pwdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(550, 550, 550)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel_NIM)
                                .addComponent(jLabel_Nama)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextField_Nama)
                                .addComponent(jTextFiel_NIM)
                                .addComponent(jTextField_umur, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jPassField1_pwd)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(0, 0, Short.MAX_VALUE)
                            .addComponent(jLabel1)
                            .addGap(37, 37, 37)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton_OK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_Kembali, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)))
                .addGap(573, 573, 573))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(204, 204, 204)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Nama)
                    .addComponent(jTextField_Nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFiel_NIM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_NIM))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jPassField1_pwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField_umur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(jButton_OK, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_Kembali, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(240, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_umurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_umurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_umurActionPerformed

    private void jPassField1_pwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPassField1_pwdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPassField1_pwdActionPerformed

    public JButton getjButton_Kembali() {
        return jButton_Kembali;
    }

    public JButton getjButton_OK() {
        return jButton_OK;
    }

    public JTextField getjTextFiel_NIM() {
        return jTextFiel_NIM;
    }

    public void setjTextFiel_NIM(JTextField jTextFiel_NIM) {
        this.jTextFiel_NIM = jTextFiel_NIM;
    }

    public JTextField getjTextField_Nama() {
        return jTextField_Nama;
    }

    public void setjTextField_Nama(JTextField jTextField_Nama) {
        this.jTextField_Nama = jTextField_Nama;
    }

    public JTextField getjTextField_umur() {
        return jTextField_umur;
    }

    public void setjTextField_umur(JTextField jTextField_umur) {
        this.jTextField_umur = jTextField_umur;
    }

    public JTextField getjTextField1_pwd() {
        return jPassField1_pwd;
    }

    public void setjPassField1_pwd(JPasswordField jPassField1_pwd) {
        this.jPassField1_pwd = jPassField1_pwd;
    }

    

    
    public void addListener(ActionListener e) {
        jButton_OK.addActionListener(e);
        jButton_Kembali.addActionListener(e);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Kembali;
    private javax.swing.JButton jButton_OK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel_NIM;
    private javax.swing.JLabel jLabel_Nama;
    private javax.swing.JPasswordField jPassField1_pwd;
    private javax.swing.JTextField jTextFiel_NIM;
    private javax.swing.JTextField jTextField_Nama;
    private javax.swing.JTextField jTextField_umur;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        Object source = e.getSource();

        if (source.equals(this.getjButton_OK())) {
            String nama = this.getjTextField_Nama().getText();
            String nim = this.getjTextFiel_NIM().getText();
            String pwd = this.getjTextField1_pwd().getText();
            int umur = Integer.parseInt(this.getjTextField_umur().getText());
            pasien = new Pasien(nama, "P"+nim, pwd, umur);
            model.getDb().savePasien(pasien);
            new PoliklinikTelkom(model);//belon
            this.dispose();
        } else if (source.equals(this.getjButton_Kembali())) {
            new PoliklinikTelkom(model);
            this.dispose();
        }
    }
}
