/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Aplikasi;
import Model.Dokter;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author Ganis
 */
public class formRegistrasiDokterAdmin extends javax.swing.JFrame implements ActionListener {

    Aplikasi model;
    Dokter dokter;
    /**
     * Creates new form formRegistrasiDokterAdmin
     */
    public formRegistrasiDokterAdmin(Aplikasi model) {
        initComponents();
        this.model = model;
        this.setLocationRelativeTo(null);
        this.setTitle("Registasi Dokter");
        
        this.setVisible(true);
        this.addListener(this);
        
        this.dokter = null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_Registrasi = new javax.swing.JLabel();
        jLabel_nama = new javax.swing.JLabel();
        jLabel_Alamat = new javax.swing.JLabel();
        jLabel_Password = new javax.swing.JLabel();
        jTextField_Nama = new javax.swing.JTextField();
        jTextField_Alamat = new javax.swing.JTextField();
        jButton_Register = new javax.swing.JButton();
        jButton_Kembali = new javax.swing.JButton();
        jPasswordField_Dokter = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel_Registrasi.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel_Registrasi.setText("Registrasi");

        jLabel_nama.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_nama.setText("Nama");

        jLabel_Alamat.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_Alamat.setText("Alamat");

        jLabel_Password.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_Password.setText("Password");

        jButton_Register.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_Register.setText("Register");

        jButton_Kembali.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_Kembali.setText("Kembali");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(516, 516, 516)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton_Register, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_Kembali, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(500, 500, 500)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel_Alamat)
                            .addComponent(jLabel_nama)
                            .addComponent(jLabel_Password))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField_Alamat)
                            .addComponent(jTextField_Nama)
                            .addComponent(jPasswordField_Dokter, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(541, 541, 541)
                        .addComponent(jLabel_Registrasi)))
                .addContainerGap(633, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(204, 204, 204)
                .addComponent(jLabel_Registrasi)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_nama)
                    .addComponent(jTextField_Nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Alamat)
                    .addComponent(jTextField_Alamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Password)
                    .addComponent(jPasswordField_Dokter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(jButton_Register, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_Kembali, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(280, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JButton getjButton_Kembali() {
        return jButton_Kembali;
    }

    public JButton getjButton_Register() {
        return jButton_Register;
    }

    public JPasswordField getjPasswordField_Dokter() {
        return jPasswordField_Dokter;
    }

    public void setjPasswordField_Dokter(JPasswordField jPasswordField_Dokter) {
        this.jPasswordField_Dokter = jPasswordField_Dokter;
    }

    public JTextField getjTextField_Alamat() {
        return jTextField_Alamat;
    }

    public void setjTextField_Alamat(JTextField jTextField_Alamat) {
        this.jTextField_Alamat = jTextField_Alamat;
    }
    
    public void addListener(ActionListener e) {
        jButton_Register.addActionListener(e);
        jButton_Kembali.addActionListener(e);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Kembali;
    private javax.swing.JButton jButton_Register;
    private javax.swing.JLabel jLabel_Alamat;
    private javax.swing.JLabel jLabel_Password;
    private javax.swing.JLabel jLabel_Registrasi;
    private javax.swing.JLabel jLabel_nama;
    private javax.swing.JPasswordField jPasswordField_Dokter;
    private javax.swing.JTextField jTextField_Alamat;
    private javax.swing.JTextField jTextField_Nama;
    // End of variables declaration//GEN-END:variables

    public JTextField getjTextField_Nama() {
        return jTextField_Nama;
    }
    
    @Override
    public void actionPerformed(ActionEvent e) {
        Object source = e.getSource();
        
        if (source.equals(this.getjButton_Register())) {
            String nama = this.getjTextField_Nama().getText();
            String alamat = this.getjTextField_Alamat().getText();
            String pwd = this.getjPasswordField_Dokter().getText();
            dokter = new Dokter(nama, ("DOKTER"+model.getListDokter().size()+1), pwd, alamat);
            model.getDb().saveDokter(dokter);
            new PoliklinikTelkom(model); //belon
            this.dispose();
        } else if (source.equals(this.getjButton_Kembali())) {
            new PoliklinikTelkom(model);
            this.dispose();
        }
    }
}
