/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Aplikasi;
import Model.Jadwal;
import Model.Pasien;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;

/**
 *
 * @author Dhino
 */
public class halamanMilihShiftJadwal3 extends javax.swing.JFrame implements ActionListener {
    Aplikasi model;
    Pasien pasien;
    Jadwal jadwal;
    /**
     * Creates new form halamanMilihShiftJadwal3
     */
    public halamanMilihShiftJadwal3(Aplikasi model, Pasien pasien, Jadwal jadwal) {
        initComponents();
        this.model = model;
        this.setLocationRelativeTo(null);
        this.setTitle("Halaman Milih Shift Jadwal");
        this.setjLabel_NamaPasien(pasien.getNamaPasien());
        this.setVisible(true);
        this.addListener(this);
        this.pasien = pasien;
        this.jadwal = jadwal;
        this.setjLabel_DokterText(jadwal.getKodeDokter());
        this.setjLabel_jamtext(jadwal.getTanggal());
        this.setjLabel_shifttext(jadwal.getShift());
        this.setjTextArea1(pasien.getKeluhan());
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_Foto = new javax.swing.JPanel();
        jLabel_Pasien = new javax.swing.JLabel();
        jLabel_NamaPasien = new javax.swing.JLabel();
        jButton_LogOut = new javax.swing.JButton();
        jButton_MelihatShiftDokter = new javax.swing.JButton();
        jLabel_jadwal = new javax.swing.JLabel();
        jLabel_simpanJadwal = new javax.swing.JLabel();
        jButton_OK = new javax.swing.JButton();
        jButton_kembali = new javax.swing.JButton();
        jLabel_shift = new javax.swing.JLabel();
        jLabel_shifttext = new javax.swing.JLabel();
        jLabel_jam = new javax.swing.JLabel();
        jLabel_dokter = new javax.swing.JLabel();
        jLabel_jamtext = new javax.swing.JLabel();
        jLabel_DokterText = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel_FotoLayout = new javax.swing.GroupLayout(jPanel_Foto);
        jPanel_Foto.setLayout(jPanel_FotoLayout);
        jPanel_FotoLayout.setHorizontalGroup(
            jPanel_FotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 127, Short.MAX_VALUE)
        );
        jPanel_FotoLayout.setVerticalGroup(
            jPanel_FotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 172, Short.MAX_VALUE)
        );

        jLabel_Pasien.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_Pasien.setText("PASIEN");

        jLabel_NamaPasien.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_NamaPasien.setText("Nama Pasien");

        jButton_LogOut.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton_LogOut.setText("LogOut");

        jButton_MelihatShiftDokter.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_MelihatShiftDokter.setText("Melihat Shift Dokter");

        jLabel_jadwal.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel_jadwal.setText("JADWAL");

        jLabel_simpanJadwal.setText("Simpan Jadwal?");

        jButton_OK.setText("OK");
        jButton_OK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_OKActionPerformed(evt);
            }
        });

        jButton_kembali.setText("KEMBALI");

        jLabel_shift.setText("Shift");

        jLabel_shifttext.setText("jLabel2");

        jLabel_jam.setText("Tanggal  :");

        jLabel_dokter.setText("Dokter    :");

        jLabel_jamtext.setText("jLabel5");

        jLabel_DokterText.setText("jLabel6");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jButton_LogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton_MelihatShiftDokter, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel_Foto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_NamaPasien)
                                    .addComponent(jLabel_Pasien))))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                        .addComponent(jLabel_jadwal)
                        .addGap(907, 907, 907))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel_shift)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel_shifttext))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_jam)
                                    .addComponent(jLabel_dokter))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_DokterText)
                                    .addComponent(jLabel_jamtext)))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 768, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel_simpanJadwal)
                        .addGap(51, 51, 51))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton_OK, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(jButton_kembali)))
                .addGap(420, 420, 420))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(jLabel_Pasien)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel_NamaPasien)
                                    .addComponent(jLabel_shift)
                                    .addComponent(jLabel_shifttext))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel_jam)
                                    .addComponent(jLabel_jamtext))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel_dokter)
                                    .addComponent(jLabel_DokterText)))
                            .addComponent(jPanel_Foto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel_jadwal)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton_LogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jButton_MelihatShiftDokter, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(38, 38, 38)
                .addComponent(jLabel_simpanJadwal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_OK)
                    .addComponent(jButton_kembali))
                .addContainerGap(76, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_OKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_OKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_OKActionPerformed

    public JButton getjButton_LogOut() {
        return jButton_LogOut;
    }

    public JButton getjButton_MelihatShiftDokter() {
        return jButton_MelihatShiftDokter;
    }

    public JButton getjButton_OK() {
        return jButton_OK;
    }

    public JButton getjButton_kembali() {
        return jButton_kembali;
    }

    public void setjLabel_DokterText(String jLabel_DokterText) {
        this.jLabel_DokterText.setText(jLabel_DokterText);
    }

    public void setjLabel_NamaPasien(String jLabel_NamaPasien) {
        this.jLabel_NamaPasien.setText(jLabel_NamaPasien);
    }

    public void setjLabel_jamtext(String jLabel_jamtext) {
        this.jLabel_jamtext.setText(jLabel_jamtext);
    }

    public void setjLabel_shifttext(String jLabel_shifttext) {
        this.jLabel_shifttext.setText(jLabel_shifttext);
    }

    public JTextArea getjTextArea1() {
        return jTextArea1;
    }

    public void setjTextArea1(String jTextArea1) {
        this.jTextArea1.setText(jTextArea1);
    }
    
    public void addListener(ActionListener e) {
        jButton_kembali.addActionListener(e);
        jButton_LogOut.addActionListener(e);
        jButton_MelihatShiftDokter.addActionListener(e);
        jButton_OK.addActionListener(e);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_LogOut;
    private javax.swing.JButton jButton_MelihatShiftDokter;
    private javax.swing.JButton jButton_OK;
    private javax.swing.JButton jButton_kembali;
    private javax.swing.JLabel jLabel_DokterText;
    private javax.swing.JLabel jLabel_NamaPasien;
    private javax.swing.JLabel jLabel_Pasien;
    private javax.swing.JLabel jLabel_dokter;
    private javax.swing.JLabel jLabel_jadwal;
    private javax.swing.JLabel jLabel_jam;
    private javax.swing.JLabel jLabel_jamtext;
    private javax.swing.JLabel jLabel_shift;
    private javax.swing.JLabel jLabel_shifttext;
    private javax.swing.JLabel jLabel_simpanJadwal;
    private javax.swing.JPanel jPanel_Foto;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        Object source = e.getSource();

        if (source.equals(this.getjButton_MelihatShiftDokter())) {
            new halamanMilihShiftJadwal1(model, pasien);
            this.dispose();
        } else if (source.equals(this.getjButton_LogOut())) {
            new PoliklinikTelkom(model);
            this.dispose();
        } else if (source.equals(this.getjButton_OK())) {
            JOptionPane.showMessageDialog(this, "Data sudah tersimpan");
            new halamanAwalPasien(model, pasien);
            this.dispose();
        } else if (source.equals(this.getjButton_kembali())) {
            new halamanMilihShiftJadwal1(model, pasien);
            this.dispose();
        }
    }
}
