/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Admin;
import Model.Aplikasi;
import Model.Dokter;
import Model.Pasien;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author Dhino
 */
public class PoliklinikTelkom extends javax.swing.JFrame implements ActionListener {
    
    Aplikasi model;
    Pasien pasien;
    Dokter dokter;
    Admin admin;

    /**
     * Creates new form PoliklinikTelkom
     */
    public PoliklinikTelkom(Aplikasi model) {
        initComponents();
        this.model = model;
        this.setLocationRelativeTo(null);
        this.setTitle("Poliklinik Telkom");
        
        this.setVisible(true);
        this.addListener(this);
        
        this.pasien = null;
        this.dokter = null;
        this.admin = null;
        
        Admin foradmin = model.getDb().getAdmin();
        this.setjLabel_foradmin("Admin: kode=" + foradmin.getKodeAdmin() + ", password=" + foradmin.getPassword());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton_RegPasien = new javax.swing.JButton();
        jLabel_LogSeb = new javax.swing.JLabel();
        jButton_RegDokter = new javax.swing.JButton();
        jLabel_Regis = new javax.swing.JLabel();
        jButton_LogPas = new javax.swing.JButton();
        jButton_LogAdDok = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel_foradmin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton_RegPasien.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton_RegPasien.setText("Pasien");

        jLabel_LogSeb.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel_LogSeb.setText("Login Sebagai :");

        jButton_RegDokter.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton_RegDokter.setText("Dokter");

        jLabel_Regis.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel_Regis.setText("Registrasi Sebagai :");

        jButton_LogPas.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton_LogPas.setText("Pasien");

        jButton_LogAdDok.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton_LogAdDok.setText("Admin/Dokter");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel1.setText("POLIKLINIK TELKOM");

        jLabel_foradmin.setText("admin");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(368, 368, 368)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel_LogSeb)
                            .addComponent(jButton_LogAdDok, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_LogPas, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(171, 171, 171)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel_Regis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_RegPasien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_RegDokter, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(448, 448, 448)
                        .addComponent(jLabel1)))
                .addContainerGap(412, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel_foradmin, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 137, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_LogSeb)
                    .addComponent(jLabel_Regis))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_LogPas, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_RegPasien, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_LogAdDok, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_RegDokter, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(256, 256, 256)
                .addComponent(jLabel_foradmin)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setjLabel_foradmin(String jLabel_foradmin) {
        this.jLabel_foradmin.setText(jLabel_foradmin);
    }
    
    public JButton getjButton_LogAdDok() {
        return jButton_LogAdDok;
    }
    
    public JButton getjButton_LogPas() {
        return jButton_LogPas;
    }
    
    public JButton getjButton_RegDokter() {
        return jButton_RegDokter;
    }
    
    public JButton getjButton_RegPasien() {
        return jButton_RegPasien;
    }
    
    public void addListener(ActionListener e) {
        jButton_LogAdDok.addActionListener(e);
        jButton_LogPas.addActionListener(e);
        jButton_RegDokter.addActionListener(e);
        jButton_RegPasien.addActionListener(e);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_LogAdDok;
    private javax.swing.JButton jButton_LogPas;
    private javax.swing.JButton jButton_RegDokter;
    private javax.swing.JButton jButton_RegPasien;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_LogSeb;
    private javax.swing.JLabel jLabel_Regis;
    private javax.swing.JLabel jLabel_foradmin;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        Object source = e.getSource();
        
        if (source.equals(this.getjButton_LogPas())) {
            new formLoginPasien(model);
            this.dispose();
        } else if (source.equals(this.getjButton_LogAdDok())) {
            new formLoginDokter(model);
            this.dispose();
        } else if (source.equals(this.getjButton_RegDokter())) {
            new formRegistrasiDokterAdmin(model);
            this.dispose();
        } else if (source.equals(this.getjButton_RegPasien())) {
            new formRegistrasiPasien(model);
            this.dispose();
        }
    }
}
